// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtgaJygmpo2KSymn5UXSUrOonyGEvMHO0',
    appId: '1:365156928489:web:2940eb8b52e310f0f71978',
    messagingSenderId: '365156928489',
    projectId: 'type-d-anurag-1786',
    authDomain: 'type-d-anurag-1786.firebaseapp.com',
    storageBucket: 'type-d-anurag-1786.appspot.com',
    measurementId: 'G-EVGH0W3CSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSSv9YDxv6cpZkNlwsvx6Y1xaT0-xbrNI',
    appId: '1:365156928489:android:053b90ab6c6c8cdaf71978',
    messagingSenderId: '365156928489',
    projectId: 'type-d-anurag-1786',
    storageBucket: 'type-d-anurag-1786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwd_eqwDTkRby1Py3KLiOxDo0Gtgm98WY',
    appId: '1:365156928489:ios:735799c183691f7ff71978',
    messagingSenderId: '365156928489',
    projectId: 'type-d-anurag-1786',
    storageBucket: 'type-d-anurag-1786.appspot.com',
    iosBundleId: 'com.example.taskDAnurag1786',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwd_eqwDTkRby1Py3KLiOxDo0Gtgm98WY',
    appId: '1:365156928489:ios:33cd63c4445cedcff71978',
    messagingSenderId: '365156928489',
    projectId: 'type-d-anurag-1786',
    storageBucket: 'type-d-anurag-1786.appspot.com',
    iosBundleId: 'com.example.taskDAnurag1786.RunnerTests',
  );
}
